import type { GameCard } from "./game-types"

export const POKEMON_CARDS: GameCard[] = [
  // Grupo 1
  {
    id: "1A",
    name: "Pikachu",
    image: "/pikachu-pokemon-card.jpg",
    category: "Electric",
    attributes: [
      { name: "Poder", value: 85 },
      { name: "Velocidad", value: 90 },
      { name: "Defensa", value: 40 },
      { name: "Rareza", value: 70 },
    ],
  },
  {
    id: "1B",
    name: "Raichu",
    image: "/raichu-pokemon-card.jpg",
    category: "Electric",
    attributes: [
      { name: "Poder", value: 90 },
      { name: "Velocidad", value: 110 },
      { name: "Defensa", value: 55 },
      { name: "Rareza", value: 65 },
    ],
  },
  {
    id: "1C",
    name: "Zapdos",
    image: "/zapdos-pokemon-card.jpg",
    category: "Electric",
    attributes: [
      { name: "Poder", value: 125 },
      { name: "Velocidad", value: 100 },
      { name: "Defensa", value: 85 },
      { name: "Rareza", value: 95 },
    ],
  },
  {
    id: "1D",
    name: "Jolteon",
    image: "/jolteon-pokemon-card.jpg",
    category: "Electric",
    attributes: [
      { name: "Poder", value: 95 },
      { name: "Velocidad", value: 130 },
      { name: "Defensa", value: 60 },
      { name: "Rareza", value: 75 },
    ],
  },
  // Grupo 2
  {
    id: "2A",
    name: "Charizard",
    image: "/charizard-pokemon-card.png",
    category: "Fire",
    attributes: [
      { name: "Poder", value: 130 },
      { name: "Velocidad", value: 100 },
      { name: "Defensa", value: 78 },
      { name: "Rareza", value: 98 },
    ],
  },
  {
    id: "2B",
    name: "Arcanine",
    image: "/arcanine-pokemon-card.jpg",
    category: "Fire",
    attributes: [
      { name: "Poder", value: 110 },
      { name: "Velocidad", value: 95 },
      { name: "Defensa", value: 80 },
      { name: "Rareza", value: 80 },
    ],
  },
  {
    id: "2C",
    name: "Moltres",
    image: "/moltres-pokemon-card.jpg",
    category: "Fire",
    attributes: [
      { name: "Poder", value: 125 },
      { name: "Velocidad", value: 90 },
      { name: "Defensa", value: 90 },
      { name: "Rareza", value: 95 },
    ],
  },
  {
    id: "2D",
    name: "Flareon",
    image: "/flareon-pokemon-card.jpg",
    category: "Fire",
    attributes: [
      { name: "Poder", value: 115 },
      { name: "Velocidad", value: 65 },
      { name: "Defensa", value: 60 },
      { name: "Rareza", value: 75 },
    ],
  },
  // Grupo 3
  {
    id: "3A",
    name: "Blastoise",
    image: "/blastoise-pokemon-card.png",
    category: "Water",
    attributes: [
      { name: "Poder", value: 120 },
      { name: "Velocidad", value: 78 },
      { name: "Defensa", value: 100 },
      { name: "Rareza", value: 92 },
    ],
  },
  {
    id: "3B",
    name: "Gyarados",
    image: "/gyarados-pokemon-card.jpg",
    category: "Water",
    attributes: [
      { name: "Poder", value: 125 },
      { name: "Velocidad", value: 81 },
      { name: "Defensa", value: 79 },
      { name: "Rareza", value: 85 },
    ],
  },
  {
    id: "3C",
    name: "Articuno",
    image: "/articuno-pokemon-card.jpg",
    category: "Water",
    attributes: [
      { name: "Poder", value: 115 },
      { name: "Velocidad", value: 85 },
      { name: "Defensa", value: 100 },
      { name: "Rareza", value: 95 },
    ],
  },
  {
    id: "3D",
    name: "Vaporeon",
    image: "/vaporeon-pokemon-card.jpg",
    category: "Water",
    attributes: [
      { name: "Poder", value: 100 },
      { name: "Velocidad", value: 65 },
      { name: "Defensa", value: 95 },
      { name: "Rareza", value: 75 },
    ],
  },
  // Grupo 4
  {
    id: "4A",
    name: "Venusaur",
    image: "/venusaur-pokemon-card.png",
    category: "Grass",
    attributes: [
      { name: "Poder", value: 115 },
      { name: "Velocidad", value: 80 },
      { name: "Defensa", value: 95 },
      { name: "Rareza", value: 92 },
    ],
  },
  {
    id: "4B",
    name: "Exeggutor",
    image: "/exeggutor-pokemon-card.jpg",
    category: "Grass",
    attributes: [
      { name: "Poder", value: 105 },
      { name: "Velocidad", value: 55 },
      { name: "Defensa", value: 85 },
      { name: "Rareza", value: 70 },
    ],
  },
  {
    id: "4C",
    name: "Victreebel",
    image: "/victreebel-pokemon-card.jpg",
    category: "Grass",
    attributes: [
      { name: "Poder", value: 100 },
      { name: "Velocidad", value: 70 },
      { name: "Defensa", value: 65 },
      { name: "Rareza", value: 68 },
    ],
  },
  {
    id: "4D",
    name: "Vileplume",
    image: "/vileplume-pokemon-card.jpg",
    category: "Grass",
    attributes: [
      { name: "Poder", value: 95 },
      { name: "Velocidad", value: 50 },
      { name: "Defensa", value: 85 },
      { name: "Rareza", value: 72 },
    ],
  },
  // Grupo 5
  {
    id: "5A",
    name: "Mewtwo",
    image: "/mewtwo-pokemon-card.png",
    category: "Psychic",
    attributes: [
      { name: "Poder", value: 150 },
      { name: "Velocidad", value: 130 },
      { name: "Defensa", value: 90 },
      { name: "Rareza", value: 100 },
    ],
  },
  {
    id: "5B",
    name: "Alakazam",
    image: "/alakazam-pokemon-card.jpg",
    category: "Psychic",
    attributes: [
      { name: "Poder", value: 135 },
      { name: "Velocidad", value: 120 },
      { name: "Defensa", value: 55 },
      { name: "Rareza", value: 88 },
    ],
  },
  {
    id: "5C",
    name: "Hypno",
    image: "/hypno-pokemon-card.jpg",
    category: "Psychic",
    attributes: [
      { name: "Poder", value: 85 },
      { name: "Velocidad", value: 67 },
      { name: "Defensa", value: 70 },
      { name: "Rareza", value: 65 },
    ],
  },
  {
    id: "5D",
    name: "Espeon",
    image: "/espeon-pokemon-card.png",
    category: "Psychic",
    attributes: [
      { name: "Poder", value: 110 },
      { name: "Velocidad", value: 110 },
      { name: "Defensa", value: 65 },
      { name: "Rareza", value: 75 },
    ],
  },
  // Grupo 6
  {
    id: "6A",
    name: "Dragonite",
    image: "/dragonite-pokemon-card.jpg",
    category: "Dragon",
    attributes: [
      { name: "Poder", value: 134 },
      { name: "Velocidad", value: 80 },
      { name: "Defensa", value: 95 },
      { name: "Rareza", value: 94 },
    ],
  },
  {
    id: "6B",
    name: "Salamence",
    image: "/salamence-pokemon-card.jpg",
    category: "Dragon",
    attributes: [
      { name: "Poder", value: 135 },
      { name: "Velocidad", value: 100 },
      { name: "Defensa", value: 80 },
      { name: "Rareza", value: 90 },
    ],
  },
  {
    id: "6C",
    name: "Garchomp",
    image: "/garchomp-pokemon-card.jpg",
    category: "Dragon",
    attributes: [
      { name: "Poder", value: 130 },
      { name: "Velocidad", value: 102 },
      { name: "Defensa", value: 95 },
      { name: "Rareza", value: 92 },
    ],
  },
  {
    id: "6D",
    name: "Flygon",
    image: "/flygon-pokemon-card.jpg",
    category: "Dragon",
    attributes: [
      { name: "Poder", value: 100 },
      { name: "Velocidad", value: 100 },
      { name: "Defensa", value: 80 },
      { name: "Rareza", value: 82 },
    ],
  },
  // Grupo 7
  {
    id: "7A",
    name: "Snorlax",
    image: "/snorlax-pokemon-card.png",
    category: "Normal",
    attributes: [
      { name: "Poder", value: 110 },
      { name: "Velocidad", value: 30 },
      { name: "Defensa", value: 110 },
      { name: "Rareza", value: 78 },
    ],
  },
  {
    id: "7B",
    name: "Tauros",
    image: "/tauros-pokemon-card.jpg",
    category: "Normal",
    attributes: [
      { name: "Poder", value: 100 },
      { name: "Velocidad", value: 110 },
      { name: "Defensa", value: 95 },
      { name: "Rareza", value: 72 },
    ],
  },
  {
    id: "7C",
    name: "Kangaskhan",
    image: "/kangaskhan-pokemon-card.jpg",
    category: "Normal",
    attributes: [
      { name: "Poder", value: 95 },
      { name: "Velocidad", value: 90 },
      { name: "Defensa", value: 80 },
      { name: "Rareza", value: 70 },
    ],
  },
  {
    id: "7D",
    name: "Eevee",
    image: "/eevee-pokemon-card.png",
    category: "Normal",
    attributes: [
      { name: "Poder", value: 55 },
      { name: "Velocidad", value: 55 },
      { name: "Defensa", value: 50 },
      { name: "Rareza", value: 85 },
    ],
  },
  // Grupo 8
  {
    id: "8A",
    name: "Machamp",
    image: "/machamp-pokemon-card.jpg",
    category: "Fighting",
    attributes: [
      { name: "Poder", value: 130 },
      { name: "Velocidad", value: 55 },
      { name: "Defensa", value: 80 },
      { name: "Rareza", value: 76 },
    ],
  },
  {
    id: "8B",
    name: "Hitmonlee",
    image: "/hitmonlee-pokemon-card.jpg",
    category: "Fighting",
    attributes: [
      { name: "Poder", value: 120 },
      { name: "Velocidad", value: 87 },
      { name: "Defensa", value: 53 },
      { name: "Rareza", value: 68 },
    ],
  },
  {
    id: "8C",
    name: "Hitmonchan",
    image: "/hitmonchan-pokemon-card.jpg",
    category: "Fighting",
    attributes: [
      { name: "Poder", value: 105 },
      { name: "Velocidad", value: 76 },
      { name: "Defensa", value: 79 },
      { name: "Rareza", value: 68 },
    ],
  },
  {
    id: "8D",
    name: "Primeape",
    image: "/primeape-pokemon-card.jpg",
    category: "Fighting",
    attributes: [
      { name: "Poder", value: 105 },
      { name: "Velocidad", value: 95 },
      { name: "Defensa", value: 60 },
      { name: "Rareza", value: 62 },
    ],
  },
]
